### ISSUE TITLE
Port A Whirlwind Tour of C++  to website

### ISSUE THREAD

**Issue by hXtreme** [cis547/cis547.github.io#23]
Port [A Whirlwind Tour of C++](https://www.cis.upenn.edu/~cis5470/cpp.doc) from google doc to a resource on our website.

## Tasks

- [ ] We want it to reside at: [software-analysis-class.org/resources/cpp](https://software-analysis-class.org/resources/cpp).
- [ ] We want the document stylized similar to other resources; ex. [course-vm](https://software-analysis-class.org/resources/course-vm)
- [ ] All links on the website to the old doc must be replaced with the above new url.
- [ ] All links on canvas to the old link should be replaced with the new url.

**Comment by joshmhanson** [comment]
@hXtreme I'm getting a permission denied error - need repository rights to push my branch

**Comment by hXtreme** [comment]
You'll need to fork the repo, push the branch to your fork and create a pr from there.
