### ISSUE TITLE
Add LLVM Primer to the website

### ISSUE THREAD

**Issue by hXtreme** [cis547/cis547.github.io#24]
Port [LLVM Primer](https://www.cis.upenn.edu/~cis5470/llvm.pdf) from google doc to a resources on our website.

## Tasks

- [ ] We want it to be available at: [software-analysis-class.org/resources/llvm-primer](https://software-analysis-class.org/resources/llvm-primer).
- [ ] It should be a pdf download
- [ ] All links on the website to the old doc must be replaced with the above new url.
- [ ] All links on canvas to the old link should be replaced with the new url.

**Comment by nathan-duddles** [comment]
Note: current link is https://www.cis.upenn.edu/~cis5470/llvm.pdf
